package com.home77.kake.bs;

/**
 * @author CJ
 */
public enum CmdType {

  //common
  VIEW_CREATE,
  VIEW_DESTORY,
  TOAST,

  // local photo presenter
  LOCAL_PHOTO_LIST_LOADING,
  LOCAL_PHOTO_LIST_LOAD_SUCCESS,
  LOCAL_PHOTO_LIST_LOAD_ERROR,

  // cloud album list presenter
  CLOUD_ALBUM_LOADING,
  CLOUD_ALBUM_LOAD_SUCCESS,
  CLOUD_ALBUM_LOAD_ERROR,
  CLOUD_ALBUM_CREATING,
  CLOUD_ALBUM_CREATE_SUCCESS,
  CLOUD_ALBUM_CREATE_ERROR,

  // user
  CHECK_CODE_COUNT_DOWN,
  PASSWORD_RESETING,
  PASSWORD_RESET_SUCCESS,
  PASSWORD_RESET_ERROR,
  REGISTERING,
  REGISTER_SUCCESS,
  REGISTER_ERROR,
}
