package com.home77.kake.base;

/**
 * @author CJ
 */
public enum CmdType {

  //common
  VIEW_CREATE,
  VIEW_DESTROY,
  VIEW_REFRESH,
  TOAST,
  LOADING,
  SHOW_MENU,
  SHOW_ALBUM_INFO,

  // local photo presenter
  LOCAL_PHOTO_LIST_LOADING,
  LOCAL_PHOTO_LIST_LOAD_SUCCESS,
  LOCAL_PHOTO_LIST_LOAD_ERROR,
  DEVICE_NOT_LINK,
  TO_PHOTO_VIEW_ACTIVITY,
  OPEN_WIFI_SETTING,

  // cloud album list presenter
  CLOUD_ALBUM_LOADING,
  CLOUD_ALBUM_LOAD_SUCCESS,
  CLOUD_ALBUM_LOAD_ERROR,
  CLOUD_ALBUM_CREATING,
  CLOUD_ALBUM_CREATE_SUCCESS,
  CLOUD_ALBUM_CREATE_ERROR,

  CLOUD_PHOTO_LIST_LOADING,
  CLOUD_PHOTO_LIST_LOAD_SUCCESS,
  CLOUD_PHOTO_LIST_LOAD_ERROR,
  SHOW_PHOTO_SELECTOR,
  SHOW_QRCODE_DIALOG,
  SHOW_MAKE_PUBLIC_DIALOG,
  SHOW_SHARE_DIALOG,
  SHOW_EDIT_PHOTO_DIALOG,
  SHOW_DELETE_PHOTO_CONFIRM_DIALOG,
  SHOW_RENAME_PHOTO_DIALOG,

  PHOTO_UPLOAD_SUCCESS,
  PHOTO_UPLOAD_ERROR,
  PHOTO_UPLOADING,

  MAKE_PANO_POSTING,
  MAKE_PANO_POST_SUCCESS,
  MAKE_PANO_POST_ERROR, SHOW_PANO_PHOTO,

  MAKE_PUBLIC_POSTING,
  MAKE_PUBLIC_SUCCESS,
  MAKE_PUBLIC_ERROR,

  PHOTO_DELETE_SUCCESS,
  PHOTO_DELETE_ERROR,

  PHOTO_RENAME_ERROR,
  PHOTO_RENAME_SUCCESS,

  ALBUM_RENAME_ERROR,
  ALBUM_RENAME_SUCCESS,

  // user
  CHECK_CODE_COUNT_DOWN,
  PASSWORD_RESETING,
  PASSWORD_RESET_SUCCESS,
  PASSWORD_RESET_ERROR,
  REGISTERING,
  REGISTER_SUCCESS,
  REGISTER_ERROR,
  LOGINING,
  LOGIN_SUCCESS,
  LOGIN_ERROR,
  RENAME_SUCCESS,
  AVATAR_UPDATING,
  AVATAR_UPDATE_SUCCESS,
  AVATAR_UPDATE_ERROR,
  SHOW_AVATAR_SELECT_DIALOG,
  SHOW_HOME_SELECT_CLOUD_ALBUM,
  SHOW_KAKE_ACTIVITY,
}
