package com.home77.kake.base;

/**
 * @author CJ
 */
public enum MsgType {
  // common
  VIEW_REFRESH,
  CLICK_BACK,
  CLICK_MENU,
  // cloud album
  CLICK_CREATE_ALBUM_DIALOG_OK,
  CLICK_MENU_IMPORT_PHOTO,
  CLICK_MENU_GENERATE_QRCODE,
  CLICK_MENU_KAKE,
  CLICK_MENU_SHARE,
  CLICK_BOTTOM_BUTTON,
  CLICK_OK_MAKE_PUBLIC_DIALOG,

  //local photo
  CLICK_LINCK_CAMERA,

  // user
  CLICK_CHECK_CODE,
  CLICK_REGISTER,
  CLICK_LOGIN,
  CLICK_SUBMIT,
  CLICK_FORGET_PASSWORD,
  CLICK_REGISTER_NOW,
  EDIT_USER_NAME_DONE,
  CLICK_AVATAR,
  CLICK_KAKE,
  CLICK_CLOUD_ALBUM,
  CLICK_USER_NAME,
  CLICK_ABOUT,
  CLICK_HELP,
  CLICK_LOGOUT,
  TAKE_AVATAR_FILE,
  //about
  CLICK_UPDATE,
}
